application: laundry
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: content/stylesheets

- url: /images
  static_dir: content/images

- url: /scripts
  static_dir: client/scripts

- url: /profiles.*
  script: controllers/profile.py

- url: /dashboard/admin
  script: controllers/admin.py

- url: /dashboard/products.*
  script: controllers/product.py

- url: /dashboard(|/orders/).*
  script: controllers/order.py 

- url: (^/$|^/services$|^/contact|^/login)
  script: controllers/home.py
  
- url: /.*
  script: controllers/not_found.py